url = https://sampleapp.tricentis.com/101/index.php
autoLinkText = Automobile
makeName = Make
epId = engineperformance
domCss = input[placeholder="MM/DD/YYYY"]
seatsXPath = /html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/section[1]/div[4]/select[1]
