url = https://sampleapp.tricentis.com/101/index.php
autoLinkText = Automobile
makeName = Make
epId = engineperformance
domCss = input[placeholder="MM/DD/YYYY"]
seatsXPath = //select[@id='numberofseats']
